abstract: Handy utilities for working with Selenium
author: Luke Closs <cpan@5thplane.com>
distribution_type: module
generated_by: Module::Install version 0.52
license: perl
module_name: WWW::Selenium::Utils
name: WWW-Selenium-Utils
no_index:
  directory:
    - inc
    - t
version: 0.08
